version: '3.8'
services:
  app:
    build: ./app
    container_name: sample-metrics-app
    ports:
      - '3001:3001'
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-local
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    depends_on:
      - app
    restart: unless-stopped
    
  grafana:
    image: grafana/grafana:9.5.0
    container_name: grafana-local
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
    ports:
      - '3006:3000'
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  grafana-storage: