global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'sample-app'
    static_configs:
      - targets: ['app:3001']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']